# Generated by Django 5.2 on 2025-04-02 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('release_date', models.DateField()),
                ('imdb_rating', models.FloatField()),
                ('poster_url', models.URLField()),
                ('genre', models.CharField(max_length=100)),
            ],
        ),
    ]
