# Generated by Django 5.2 on 2025-04-13 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0011_reviewcomment_reviewlike'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='video_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
